/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_v1_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Summary */
        get: operations["system_summary_v1_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbstainedAnswer */
        AbstainedAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "abstained";
            /** Message */
            message: string;
            /** Suggestions */
            suggestions: string[];
            trace: components["schemas"]["TraceSummary"];
        };
        /** AnswerBlock */
        AnswerBlock: {
            /** Source Ids */
            source_ids: string[];
            /** Text */
            text: string;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Question */
            question: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Behavior Passed */
            behavior_passed?: number | null;
            /** Behavior Total */
            behavior_total?: number | null;
            /** Generated At */
            generated_at?: string | null;
            /** Retrieval Recall At 3 */
            retrieval_recall_at_3?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "unavailable";
            /** Version */
            version: string;
        };
        /** GroundedAnswer */
        GroundedAnswer: {
            /** Blocks */
            blocks: components["schemas"]["AnswerBlock"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "grounded";
            /** Sources */
            sources: components["schemas"]["Source"][];
            trace: components["schemas"]["TraceSummary"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Build Version */
            build_version: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** RetrievalSummary */
        RetrievalSummary: {
            /** Limit */
            limit: number;
            /** Score Kind */
            score_kind: string;
            /**
             * Score Order
             * @enum {string}
             */
            score_order: "lower_is_better" | "higher_is_better" | "not_applicable";
            /** Strategy */
            strategy: string;
        };
        /** RetrievedItem */
        RetrievedItem: {
            /** Rank */
            rank: number;
            /** Raw Score */
            raw_score?: number | null;
            /** Source Id */
            source_id: string;
        };
        /** Source */
        Source: {
            /** Content Path */
            content_path: string;
            /** Excerpt */
            excerpt: string;
            /** Section */
            section: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
        };
        /** SystemSummary */
        SystemSummary: {
            /** Build Version */
            build_version: string;
            evaluation: components["schemas"]["EvaluationSummary"];
            /** Limitations */
            limitations: string[];
            /** Next Experiment */
            next_experiment: string;
            retrieval: components["schemas"]["RetrievalSummary"];
        };
        /** TraceSummary */
        TraceSummary: {
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Generation Ms */
            generation_ms: number;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /**
             * Provider Mode
             * @enum {string}
             */
            provider_mode: "mock" | "live";
            /** Retrieval Ms */
            retrieval_ms: number;
            /** Retrieval Strategy */
            retrieval_strategy: string;
            /** Retrieved */
            retrieved: components["schemas"]["RetrievedItem"][];
            /** Score Kind */
            score_kind: string;
            /**
             * Score Order
             * @enum {string}
             */
            score_order: "lower_is_better" | "higher_is_better" | "not_applicable";
            /** Total Ms */
            total_ms: number;
            /** Trace Id */
            trace_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    answer_v1_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundedAnswer"] | components["schemas"]["AbstainedAnswer"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    system_summary_v1_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSummary"];
                };
            };
        };
    };
}
